### ISSUE TITLE
Error with davejamesmiller/laravel-breadcrumbs

### ISSUE THREAD

**Issue by pontmerci** [orchidsoftware/platform#1170]
**Describe the bug**
I dont know what this error!

**To Reproduce**

  1.composer install

**Expected behavior**
Install dependecies.

**Screenshots**

PHP Warning:  Uncaught ErrorException: require(/var/www/routes/breadcrumbs.php): failed to open stream: No such file or directory in /Users/david/PROYECTOS/admin/gestion7/vendor/davejamesmiller/laravel-breadcrumbs/src/BreadcrumbsServiceProvider.php:94
Stack trace:
#0 /Users/david/PROYECTOS/admin/gestion7/vendor/davejamesmiller/laravel-breadcrumbs/src/BreadcrumbsServiceProvider.php(94): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'require(/var/ww...', '/Users/david/PR...', 94, Array)
#1 /Users/david/PROYECTOS/admin/gestion7/vendor/davejamesmiller/laravel-breadcrumbs/src/BreadcrumbsServiceProvider.php(94): require()
#2 /Users/david/PROYECTOS/admin/gestion7/vendor/davejamesmiller/laravel-breadcrumbs/src/BreadcrumbsServiceProvider.php(63): DaveJamesMiller\Breadcrumbs\BreadcrumbsServiceProvider->registerBreadcrumbs()
#3 [internal function]: DaveJamesMiller\Breadcrumbs\BreadcrumbsServiceProvider->boot()
#4 /Users/david/PROYECTOS/admin/gestion7/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php in /Users/david/PROYECTOS/admin/gestion7/vendor/davejamesmiller/laravel-breadcrumbs/src/BreadcrumbsServiceProvider.php on line 94
PHP Fatal error:  DaveJamesMiller\Breadcrumbs\BreadcrumbsServiceProvider::registerBreadcrumbs(): Failed opening required '/var/www/routes/breadcrumbs.php' (include_path='.:/usr/local/Cellar/php@7.3/7.3.12/share/php@7.3/pear') in /Users/david/PROYECTOS/admin/gestion7/vendor/davejamesmiller/laravel-breadcrumbs/src/BreadcrumbsServiceProvider.php on line 94

   UnexpectedValueException 

  There is no existing directory at "/var/www/storage/logs" and its not buildable: Permission denied

  at vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:172
    168|             set_error_handler([$this, 'customErrorHandler']);
    169|             $status = mkdir($dir, 0777, true);
    170|             restore_error_handler();
    171|             if (false === $status && !is_dir($dir)) {
  > 172|                 throw new \UnexpectedValueException(sprintf('There is no existing directory at "%s" and its not buildable: '.$this->errorMessage, $dir));
    173|             }
    174|         }
    175|         $this->dirCreated = true;
    176|     }

      +8 vendor frames 
  9   app/Exceptions/Handler.php:39
      Illuminate\Foundation\Exceptions\Handler::report(Object(Symfony\Component\ErrorHandler\Error\FatalError))

      +3 vendor frames 
  13  [internal]:0
      Illuminate\Foundation\Bootstrap\HandleExceptions::handleShutdown()

   Whoops\Exception\ErrorException 

  DaveJamesMiller\Breadcrumbs\BreadcrumbsServiceProvider::registerBreadcrumbs(): Failed opening required '/var/www/routes/breadcrumbs.php' (include_path='.:/usr/local/Cellar/php@7.3/7.3.12/share/php@7.3/pear')

  at vendor/davejamesmiller/laravel-breadcrumbs/src/BreadcrumbsServiceProvider.php:94
    90|         $breadcrumbs = $this->app->make(BreadcrumbsManager::class);
    91| 
    92|         // Support both a single string filename and an array of filenames (e.g. returned by glob())
    93|         foreach ((array) $files as $file) {
  > 94|             require $file;
    95|         }
    96|     }
    97| }
    98| 

      +1 vendor frames 
  2   [internal]:0
      Whoops\Run::handleShutdown()

**Comment by pontmerci** [comment]
delete files in bootstrap/cache...
